# -*- coding: utf-8 -*-
"""DPO_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nses8GNd5FUxPpE79IoujjlOes8Fn6lw
"""

!pip install transformers accelerate peft trl datasets

from google.colab import drive
drive.mount('/content/drive')

formatted_data

import os
import json

# Step 1: Define your formatting function (output ONLY prompt, chosen, rejected)
def formatdata(data):
    prompt = (
        f"Given this dialogue with a user contradiction, the contradiction happens between "
        f"{data['Contradiction']['curr_pref']} and {data['Contradiction']['prev_pref']} "
        f"with certainty level {data['Contradiction']['certainty']}. "
        f"Generate the response."
    )
    return {
        'prompt': prompt,
        'chosen': data['Response']['preferred_response'],
        'rejected': data['Response']['dispreferred_response']
    }

# Step 2: Safe wrapper for formatting
def safe_format(entry, file_path):
    try:
        return formatdata(entry)
    except Exception as e:
        print(f"⚠️ Error formatting entry in {file_path}: {e}")
        return None

# Step 3: Root directory (update this to your Google Drive folder path)
root_dir = '/content/drive/MyDrive/output'

# Step 4: Storage
formatted_data = []
file_count = 0

# Step 5: Recursive walk through subfolders
for subdir, _, files in os.walk(root_dir):
    print(f"🔍 Searching in: {subdir}")
    for filename in files:
        if filename.endswith('.json'):
            file_count += 1
            file_path = os.path.join(subdir, filename)
            print(f"📂 Processing: {file_path}")
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)

                    # Since each file is a single dictionary
                    if isinstance(data, dict):
                        formatted = safe_format(data, file_path)
                        if formatted:
                            formatted_data.append(formatted)
            except Exception as e:
                print(f"❌ Failed to load JSON from {file_path}: {e}")
        else:
            print(f"⏩ Skipping non-JSON file: {filename}")

# Step 6: Save all formatted outputs to a JSONL file
output_path = 'all_formatted_data.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for item in formatted_data:
        f.write(json.dumps(item) + '\n')

print(f"\n📄 Total JSON files processed: {file_count}")
print(f"✅ Saved {len(formatted_data)} formatted items to {output_path}")

from transformers import AutoTokenizer, AutoModelForCausalLM
from trl import DPOTrainer, DPOConfig
from datasets import load_dataset
import torch

# 1. Load tokenizer and base model (Qwen)
model_name = "Qwen/Qwen1.5-1.8B"  # or "Qwen/Qwen1.5-7B" if you have resources
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_name, trust_remote_code=True)

# 2. (Optional) Use PEFT (LoRA) for efficient training
from peft import LoraConfig, get_peft_model, TaskType
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["c_proj", "c_attn", "q_proj", "v_proj"],  # modify as needed
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)
model = get_peft_model(model, lora_config)

# 3. Load or create dataset with "prompt", "chosen", and "rejected" fields
# You can replace this with your own dataset (CSV/JSON or custom loading function)
dataset = formatted_data  # should return dict with keys: 'prompt', 'chosen', 'rejected'

# 4. Configure DPO training
dpo_config = DPOConfig(
    beta=0.1,
    max_length=1024,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    learning_rate=5e-5,
    num_train_epochs=3,
    logging_steps=10,
    evaluation_strategy="no",
    save_strategy="epoch",
    output_dir="./qwen-dpo-checkpoints"
)

# 5. Initialize and run the DPO trainer
trainer = DPOTrainer(
    model=model,
    ref_model=None,  # uses a frozen copy of the original model if None
    args=dpo_config,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset.get("validation", None),
)

trainer.train()

